function getTilesetsList()
{
	let arrays = [
		{
			name: 'test',
			resource: './SampleData/Cesium3DTiles/wgs84/test/test.json'
		}, {
			name: 'accuracy_cityholl',
			resource: './SampleData/Cesium3DTiles/wgs84/accuracy/test.json'
		}, {
			name: 'anyang_around_201119',
			resource: './SampleData/Cesium3DTiles/wgs84/anyang_around/anyang_around.json'
		}, {
			name: 'busan_echocity',
			resource: './SampleData/Cesium3DTiles/wgs84/busan_echocity/test.json'
		}, {
			name: 'busan_echocity_b_d',
			resource: './SampleData/Cesium3DTiles/wgs84/busan_echocity_b_d/test.json',
		}, {
			name: 'busan_echocity_model',
			resource: './SampleData/Cesium3DTiles/wgs84/부산_에코시티모델/test.json',
		}, {
			name: 'busan_echocity_model_b_d',
			resource: './SampleData/Cesium3DTiles/wgs84/부산_에코시티모델_d_b/test.json',
		}, {
			name: 'busan_echocity_model_indoor',
			resource: './SampleData/Cesium3DTiles/wgs84/부산_에코시티모델_indoor/test.json',
		}, {
			name: 'building_solid',
			resource: './SampleData/Cesium3DTiles/wgs84/building_solid/korea.json',
			styleName: 'building_solid'
		}, {
			name: 'daeduck_bridge',
			resource: './SampleData/Cesium3DTiles/wgs84/daeduck_bridge/daeduck_bridge.json'
		}, {
			name: 'dokdo',
			resource: './SampleData/Cesium3DTiles/wgs84/dokdo/dokdo.json'
		}, {
			name: 'incheon_0827',
			resource: './SampleData/Cesium3DTiles/wgs84/incheon_0827/incheon_0827.json'
		}, {
			name: 'jeonju_road_0603',
			resource: './SampleData/Cesium3DTiles/wgs84/jeonju_road/test.json'
		}, {
			name: 'pnts_cheongju_도로_small',
			resource: './SampleData/Cesium3DTiles/wgs84/cheongju_pnts_small/tileset.json'
		}, {
			name: 'sejongbldmap',
			resource: './SampleData/Cesium3DTiles/wgs84/sejongbldmap/sejongbldmap.json'
		}, {
			name: 'yeouido_small',
			resource: './SampleData/Cesium3DTiles/wgs84/yeouido_small/tileset.json'
		}, {
			name: 'yeouido_small_draco',
			resource: './SampleData/Cesium3DTiles/wgs84/yeouido_small_draco/tileset.json'
		}, {
			name: 'yeouido_small_basisu',
			resource: './SampleData/Cesium3DTiles/wgs84/yeouido_small_basisu/yeouido_small_basisu.json'
		}, {
			name: 'yeouido_small_basisu_draco',
			resource: './SampleData/Cesium3DTiles/wgs84/yeouido_small_basisu_draco/test.json'
		}, {
			name: 'yeouido_2108',
			resource: './SampleData/Cesium3DTiles/wgs84/yeouido_2108/test.json'
		}, {
			name: 'yeouido_attribute_d_b',
			resource: './SampleData/Cesium3DTiles/wgs84/yeouido_attribute_d_b/test.json'
		}, {
			name: 'yeouido_2201',
			resource: './SampleData/Cesium3DTiles/wgs84/yeouido_2201/test.json'
		}, {
			name: 'yeouido_2201_b_d',
			resource: './SampleData/Cesium3DTiles/wgs84/yeouido_2201_b_d/test.json'
		}, {
			name: 'smart_village_b3dm_skp',
			resource: './SampleData/Cesium3DTiles/wgs84/smart_village_b3dm_skp/tileset.json'
		}, {
			name: 'smart_village_b3dm_skp_b',
			resource: './SampleData/Cesium3DTiles/wgs84/smart_village_b3dm_skp_b/tileset.json'
		}, {
			name: 'smart_village_b3dm_skp_d_b',
			resource: './SampleData/Cesium3DTiles/wgs84/smart_village_b3dm_skp_d_b/tileset.json'
		}, {
			name: 'yeouido_2108_bas_drc',
			resource: './SampleData/Cesium3DTiles/wgs84/yeouido_2108_bas_drc/test.json'
		}, {
			name: '대전소방서',
			resource: './SampleData/Cesium3DTiles/wgs84/대전소방서/test.json'
		}, {
			name: '대전소방서_d_b',
			resource: './SampleData/Cesium3DTiles/wgs84/대전소방서_d_b/test.json'
		}, {
			name: '대전소방서_모델',
			resource: './SampleData/Cesium3DTiles/wgs84/대전소방서_모델/test.json'
		}, {
			name: '광화문일대_0726',
			resource: './SampleData/Cesium3DTiles/wgs84/광화문일대_0726/test.json'
		}, {
			name: '광화문일대_0726_drc',
			resource: './SampleData/Cesium3DTiles/wgs84/광화문일대_0726_drc/test.json'
		}, {
			name: '광화문일대_0726_drc_basisu',
			resource: './SampleData/Cesium3DTiles/wgs84/광화문일대_0726_drc_basisu/test.json'
		}, {
			name: 'high_여산휴게소',
			resource: './SampleData/Cesium3DTiles/wgs84/여산휴게소/test.json'
		}, {
			name: 'high_여산휴게소_b_d',
			resource: './SampleData/Cesium3DTiles/wgs84/여산휴게소_b_d/test.json'
		}, {
			name: 'test_i3dm',
			resource: './SampleData/Cesium3DTiles/wgs84/i3dm/i3dm.json'
		}, {
			name: 'test_i3dm_yeouido_tree_0910',
			resource: './SampleData/Cesium3DTiles/wgs84/yeouido_tree_0910/yeouido_tree_0910.json'
		}, {
			name: 'test_i3dm_multinode_0915',
			resource: './SampleData/Cesium3DTiles/wgs84/multinode_0915/multinode_0915.json'
		}, {
			name: 'test_pnts_usa',
			resource: './SampleData/Cesium3DTiles/wgs84/pnts/tileset.json'
		}, {
			name: 'test_lastDepth',
			resource: './SampleData/Cesium3DTiles/wgs84/lastdepth/test.json'
		}, {
			name: 'test_시계열',
			resource: './SampleData/Cesium3DTiles/wgs84/시계열/test.json',
			styleName: 'building_TimeSeries'
		}, {
			name: 'test_cesium_TilesetOfTilesets',
			resource: './SampleData/Cesium3DTiles/Tilesets/TilesetOfTilesets/tileset.json'
		}, {
			name: 'vworld_영등포구_Tilesets',
			resource: 'http://xdworld.vworld.kr:8080/TDServer/services/facility_LOD4/Seoul-202107/Yeongdeungpo-gu/tileset.json'
		}, {
			name: 'vworld_Tilesets',
			memo: '아마도, 전국데이터. cesium에서 초기뷰위치가 이상한테 있는데, 대한민국으로 찾아서 오면 보임.',
			resource: 'http://xdworld.vworld.kr:8080/TDServer/services/facility_LOD4/vworld_3d_facility.json'
		}, {
			name: 'next_sample_MultipleContents',
			// Position the tileset on the globe.
			modelMatrix : Cesium.Transforms.eastNorthUpToFixedFrame( Cesium.Cartesian3.fromDegrees(-75.1596759, 39.9509025, 0.25) ),			
			resource: './SampleData/Cesium3DTiles/next/MultipleContents/tileset.json'
		}, {
			name: 'next_sample_TilesetWithTileMetadata',
			resource: './SampleData/Cesium3DTiles/next/TilesetWithTileMetadata/tileset.json'
		}
	];
	
	return arrays;
}
